### PR TITLE
Provenance (needs CMSSW PR#20444)

### PR DESCRIPTION
**Pull request by gpetruc**
needs https://github.com/cms-sw/cmssw/pull/20444

seems to add ~2Mb to the file size after LZMA compression (now testing on 50k events to check it stays the same): maybe we can make it optional in case people want to run the Nano privately with finer splitting and don't want this overhead?

### CODE REVIEW

**Comment by arizzi** [comment]
what is the effect of hadd ? it duplicates it?

**Comment by gpetruc** [comment]
no idea... also, it seems like edmProvDump doesn't understand it yet, so I'll ask David to check if what I coded makes sense.

**Comment by arizzi** [comment]
having edmProvDump understanding it is a required feature to allow crab-publish

**Comment by gpetruc** [comment]
Tests on 10k and 50k events compared:
 * http://gpetrucc.web.cern.ch/gpetrucc/micro/nano_test_10k.html
 * http://gpetrucc.web.cern.ch/gpetrucc/micro/nano_test_50k.html
&rarr; the provenance is a constant offset of 2 Mb.

Incidentally, we get ~10% better compression of per-event data in 50k events than in 10k

**Comment by gpetruc** [comment]
fixed with Dan's suggestion, now edmProvDump works, so this PR can be merged when we move to 94X

**Comment by gpetruc** [comment]
merged in 94X branch

**Pull request closed without merging**
